"""empty message

Revision ID: 26c93e90a233
Revises: 52de590f607e
Create Date: 2022-10-30 23:25:21.653161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c93e90a233'
down_revision = '52de590f607e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parqueadero', sa.Column('direccion', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parqueadero', 'direccion')
    # ### end Alembic commands ###
