"""empty message

Revision ID: 2eda53d24852
Revises: 86f369e0450d
Create Date: 2022-11-22 17:40:25.503831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eda53d24852'
down_revision = '86f369e0450d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento_vehiculo', sa.Column('placa', sa.String(length=20), nullable=True))
    op.add_column('parqueadero', sa.Column('nit', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parqueadero', 'nit')
    op.drop_column('movimiento_vehiculo', 'placa')
    # ### end Alembic commands ###
