"""empty message

Revision ID: 52de590f607e
Revises: 960d4193a85e
Create Date: 2022-10-04 22:28:22.773776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52de590f607e'
down_revision = '960d4193a85e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movimiento_vehiculo', sa.Column('parqueadero_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimiento_vehiculo', 'parqueadero', ['parqueadero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimiento_vehiculo', type_='foreignkey')
    op.drop_column('movimiento_vehiculo', 'parqueadero_id')
    # ### end Alembic commands ###
