"""empty message

Revision ID: 7bac40cd2dba
Revises: 46e23bbbe799
Create Date: 2022-11-02 19:38:01.602595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bac40cd2dba'
down_revision = '46e23bbbe799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fecha_creacion')
    # ### end Alembic commands ###
