"""empty message

Revision ID: 86f369e0450d
Revises: 29cd5713c313
Create Date: 2022-11-15 13:49:21.467775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86f369e0450d'
down_revision = '29cd5713c313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarifa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=True),
    sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('valor_minuto', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_plena', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('valor_mensualidad', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_funcionario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipo_funcionario_id'], ['tipo_funcionario.id'], ),
    sa.ForeignKeyConstraint(['tipo_vehiculo_id'], ['tipovehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_a_pagar', sa.Numeric(precision=20, scale=2), nullable=True),
    sa.Column('movimiento_id', sa.Integer(), nullable=True),
    sa.Column('parqueadero_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movimiento_id'], ['movimiento_vehiculo.id'], ),
    sa.ForeignKeyConstraint(['parqueadero_id'], ['parqueadero.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('tipo_funcionario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'tipo_funcionario', ['tipo_funcionario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'tipo_funcionario_id')
    op.drop_table('factura')
    op.drop_table('tarifa')
    op.drop_table('tipo_funcionario')
    # ### end Alembic commands ###
