"""empty message

Revision ID: ad7dcdfbe915
Revises: 26c93e90a233
Create Date: 2022-11-01 16:49:11.783551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7dcdfbe915'
down_revision = '26c93e90a233'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('es_propietario', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('parqueadero_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'parqueadero', ['parqueadero_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'parqueadero_id')
    op.drop_column('user', 'es_propietario')
    # ### end Alembic commands ###
