"""empty message

Revision ID: bf7a2db93fcd
Revises: 2eda53d24852
Create Date: 2022-11-22 19:58:54.574921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7a2db93fcd'
down_revision = '2eda53d24852'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('factura', sa.Column('minutos', sa.Integer(), nullable=True))
    op.add_column('movimiento_vehiculo', sa.Column('tipo_vehiculo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movimiento_vehiculo', 'tipovehiculo', ['tipo_vehiculo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movimiento_vehiculo', type_='foreignkey')
    op.drop_column('movimiento_vehiculo', 'tipo_vehiculo_id')
    op.drop_column('factura', 'minutos')
    # ### end Alembic commands ###
